pointfreeco/swift-case-paths

Sources/CasePaths/Operators.swift, Tests/CasePathsTests/CasePathsTests.swift
After using case paths in projects where they often appear alongside key paths, it's nice to be able to annotate them with `/` as often as possible. This PR introduces an "identity" `/` operator for case paths to unlock this ability.
For example, in interfaces that take key paths and case paths, it is common to leave either fixed. For state this is straightforward:
``` swift
// Leave state fixed
reducer.pullback(state: \.self, action: /SuperAction.subAction)
```
For actions, you have a couple choices:
``` swift
// Leave action fixed with static `self`. No `/` identifying the case path
reducer.pullback(state: \SuperState.subState, action: .self)
// Leave action fixed with "long"-hand syntax. Trick uses operator overload on `Enum.Type`
reducer.pullback(state: \SuperState.subState, action: …
```
=> Case Path Shorthand Syntax

Package.swift
This adds another library, `CasePath-dynamic`, so that we can work around some SPM bugs.
=> Work around SPM bugs with static libraries

Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
A fix for #11 
A check is added before instantiating a value with a memory layout size of `0`. 
This new check ensures we do not attempt to instantiate a value from an uninhabited enum, which is what was causing the crash.
A new test is added which attempts to extract associated values from both `Never` and an equivalent, uninhabited custom type.
This test will trigger a Swift 5.3 crash without the framework changes, but passes with the changes applied.
=> Swift 5.3 crash

Makefile, Sources/CasePaths/EnumReflection.swift
Looks like there's a Swift/`Mirror` bug that causes a leak if you destructure the tuple that is `mirror.children.first`. Luckily we can work around.
Fixes #19
=> Fix memory leak due to mirror destructuring.

Sources/CasePaths/Operators.swift, Tests/CasePathsTests/CasePathsTests.swift
We've found this to be useful. Maybe we'll come up with a better non-operator operation in the future, but this seems good to have regardless.
=> Add pattern matching operator

Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
Our reflection mechanism currently goes pretty far out of its way to handle cases that it probably shouldn't:
- We currently produce reflective identity case paths for the identity function:
```swift
CasePath.self == CasePath.case { $0 }
```
We should always prefer `.self`, which is faster.
- We currently produce reflective appended case paths by recursively traversing the root mirror:
```swift
/A.b .. /B.c == CasePath.case { .b(.c($0)) }
```
We should always prefer `..` (or `CasePath.appending(path:)`)
- We allow "holes" to be filled on multi-payload enum cases:
```swift
CasePath.case { .color($0, "fill") }.extract(from: .foo(.red, "fill")) == .red
```
We should not support this kind of extraction.
Reflection is already quite slow, so let's improve performance a little by shedding this …
=> Breaking Change: Simplify Reflection

Makefile, Sources/CasePaths/Operators.swift, Tests/CasePathsTests/CasePathsTests.swift
This changes `/` overloads to selectively use `@_disfavoredOverload`, which generally allows `/Foo.bar` to resolve to a case path without the ambiguity of key path-like "case path syntax" for extraction (like in `compactMap(/Result.success)`).
=> Eliminate `/` ambiguity via disfavored overloads

Sources/CasePaths/CasePath.swift, Tests/CasePathsTests/CasePathsTests.swift
Makes things a lil prettier when working with case paths in playgrounds, etc.
=> Conform CasePath to CustomStringConvertible

.gitignore, .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, .swiftpm/xcode/xcshareddata/xcschemes/CasePaths.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-case-paths-Package.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-case-paths-benchmark.xcscheme, Package.resolved, Package.swift, Package@swift-5.1.swift, Sources/CasePaths/EnumReflection.swift, Sources/swift-case-paths-benchmark/main.swift, Tests/CasePathsTests/CasePathsTests.swift
This code speeds up reflective case paths in a couple ways:
- We were previously constructing the "identity" of a case path's case by accumulating labels off a value's mirror, but we recently found some runtime metadata APIs that can compute the "tag" of an enum much more efficiently, so we can lean on that instead.
- Computing the enum tag can be done before we reflect on a value, so we can avoid that more intense work so long as we have previously successfully extracted a value from the case path. Upon the first successful extraction we can cache the case path's tag and use it to bail out early when future extractions don't match.
This PR also includes benchmarks that could be helpful when we make changes/improvements in the future.
=> Improve reflection with Swift runtime and caching

.swiftpm/xcode/xcshareddata/xcschemes/CasePaths.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-case-paths-Package.xcscheme, Package.swift, Package@swift-5.1.swift, Sources/CCasePaths/Builtin_NativeObject_metadata.c, Sources/CCasePaths/include/Builtin_NativeObject_metadata.h, Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
The destructiveProjectEnumData function in the enum value witness table
transforms an enum value into its associated values in place, by zeroing
out any enum tag bits stored in the payload area of the value.
We can use this function after verifying that the tag of the enum
value is the expected tag. This means we still have to use the
Mirror-and-embed strategy until we can cache the expected tag.
Performance without this commit, on my iMac Pro:
```
name               time        std        iterations
----------------------------------------------------
Success.Manual       34.000 ns ± 232.27 %    1000000
Success.Reflection 3095.000 ns ±  22.64 %     470183
Failure.Manual       36.000 ns ± 167.71 %    1000000
Failure.Reflection   83.000 ns ± 152.31 %    1000000
```
Performance with this …
=> use destructiveProjectEnumData value witness function

.swiftpm/xcode/xcshareddata/xcschemes/CasePaths.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-case-paths-Package.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-case-paths-benchmark.xcscheme, Package.swift, Package@swift-5.1.swift, Sources/CCasePaths/Builtin_NativeObject_metadata.c, Sources/CCasePaths/include/Builtin_NativeObject_metadata.h, Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
This branch is not ready for merging. I'm creating this pull request only to make it available for discussion.
I found example uses of `swift_getTypeByMangledNameInContext` in [the Reflect package](https://github.com/wickwirew/Runtime) and have made some progress toward using it to replace the use of `Mirror`.
In its current state, this branch has several failing tests, all related to associated value labels. I've outlined what's wrong and what needs to be done in the commit message and code comments.
=> eliminate the use of Mirror

Sources/CasePaths/EnumReflection.swift, Sources/CasePaths/Operators.swift, Sources/swift-case-paths-benchmark/main.swift, Tests/CasePathsTests/CasePathsTests.swift
This does some stylistic cleanup from @mayoff's excellent PR, #37.
- Prefer implicit `return`
- Prefer explicit `self`
- Minimize comments. @mayoff's literate style was very helpful in getting an understanding of some of the code, and will live in the history of the project. We can consider bringing back context in the future if we find any of it helpful, but let's minimize comments for now.
@mayoff If you're cool with this, lemme know and I'll merge! A quick once-over to make sure I didn't break anything or make any incorrect assumptions would be helpful. All the tests appear to still pass.
=> Stylistic cleanup for metadata extraction

Sources/CasePaths/EnumReflection.swift, Sources/CasePaths/Operators.swift, Tests/CasePathsTests/CasePathsTests.swift
Swift promotes (A) -> B to (A) -> B? if necessary to make a statement
type-check. This can lead to an enum case initializer being promoted and
making extract erroneously return nil. Fixing it is hard, so instead I'm
detecting the problem and asserting.
Fixes #40.
=> fix issue #40 (case initializer promoted to return Optional)

Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
Swift can promoted a function taking an Optional argument to a function
taking a non-Optional argument. For example, it can promote
`Result<String?, Error>.success` from
`(String?) -> Result<String?, Error>` to
`(String) -> Result<String?, Error>`.
This commit handles that scenario properly.
Fixes #42.
=> (#42) handle embed's argument being promoted out of Optional

.swiftpm/xcode/xcshareddata/xcschemes/swift-case-paths-Package.xcscheme, Sources/CasePaths/EnumReflection.swift, Sources/CasePaths/Operators.swift, Tests/CasePathsTests/CasePathsTests.swift
This PR contains a few things in preparation of a 0.6.0, to address the optional promotion issues discovered in #40 (fixed in #41) and #42 (fixed in #43).
First, I removed the new `CasePath.optionalCase` helper because in general we want to remove surface area outside case path literal syntax. Additionally, the following existing functions have been deprecated:
- `CasePath<Root, Value>.case(embed:)`
- `CasePath<Root, Void>.case(root:)
- `extract(_:)`
- `extract(case:from:)`
Instead, users should always prefer case path literal syntax (`/Root.caseName`) or invoke the case path's extract method (`casePath.extract(from:)`).
While reorganizing, I also swapped the void-extracting case path initializers for ones that check the enum tag.
=> Clean up helpers, deprecate old extraction code, speed up `Void` extraction

Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
This fixes #45 and hopefully doesn't introduce new problems 😬. We were entering into an infinite loop when trying to extract a different case from an enum value that held an optional.
For example, trying to extract `/Result.failure` from a `Result<Int?, Error>` caused the case path to be promoted to `CasePath<Result<Int?, Error>, Error?>`, and then recursively promoted to `CasePath<Result<Int?, Error>, Error??>`, and then `CasePath<Result<Int?, Error>, Error???>`, etc...
/cc @mayoff
=> Fix optional prompt when extracting different case.

Sources/CasePaths/CasePath.swift, Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
This adds a method on `CasePath` that can take a mutable enum root and mutate its associated value in a closure.
It's proven to be quite helpful when working with mutable enum state in the Composable Architecture, especially when it comes to testing.
=> Add CasePath.modify

Sources/CasePaths/EnumReflection.swift
We were seeing some strange extraction issues on Linux and it appears to be related to using `UInt` vs. `UInt32`.
=> Fix Linux reflection bug in tuple metadata alignment

Sources/CasePaths/EnumReflection.swift
Workaround for highlighting/indentation issues mentioned in #81.
While we have a deprecated static `case` function we could un-deprecate, it doesn't read nicely when case paths needs to be appended, and the type needs to be fully-qualified:
```swift
CasePath.case(Action.response).appending(path: .case(Result.success))
^^^^     ^^^^
```
This PR introduces initializers that can be used instead of `/`.
```swift
CasePath(Action.response).appending(path: .init(Result.success))
```
Hopefully `/` will still be useful in the future, and these Xcode bugs are fixed quickly, but that doesn't mean we shouldn't provide an ergonomic solution in the meantime.
=> Introduce initializer escape hatch for Xcode 14b1

Sources/CasePaths/CasePaths.swift, Sources/CasePaths/Operators.swift, Tests/CasePathsTests/CasePathsTests.swift
Enables shorthands `.some` and `/.some` for `/Optional.some`. This has come up in the past so it seems handy enough to ship.
=> Add CasePath.some, for unwrapping optionals

.github/workflows/ci.yml, Makefile, Sources/CasePaths/CasePath.swift, Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
We can make `CasePath` sendable by locking around the part where we memoize some data from the runtime metadata. There's a chance we missed other parts that need locking, so feel free to let us know if you spot something!
Fixes #89
=> Make CasePath sendable

Makefile, Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift
Fixes #72.
In release builds, Swift <=5.7 may return the wrong tag for single-case enums that nest another enum. We can work around this by always returning "0" as the tag for single case enums.
=> Workaround for runtime returning wrong enum tag

Sources/CasePaths/EnumReflection.swift
This PR begins to expose an SPI interface for some of the enum reflection machinery that was internal. We have a bunch of tools that recreate the `enumTag` functionality in each respective repo, but those libraries typically also depend on case paths, so it'd be simpler to get the functionality directly.
=> Reflection SPI

Sources/CasePaths/Internal/OpenExistential.swift, Sources/CasePaths/XCTUnwrap.swift, Tests/CasePathsTests/XCTModifyTests.swift
This PR introduces a more streamlined way to perform an in-place mutation of a case in an enum when in a testing context:
```swift
try XCTModify(&result, case: /Result.success) {
$0 += 1
}
```
You should think of `XCTModify` as a companion to `XCTUnwrap` as it allows you to safely unwrap a case from an enum, and then further apply a mutation. This helper will be very useful for the navigation tools being built for TCA.
=> Introducing XCTModify

Sources/CasePaths/EnumReflection.swift, Tests/CasePathsTests/CasePathsTests.swift, Tests/CasePathsTests/ReflectionTests.swift
This PR reworks some of the extraction logic for case paths and exposes a `@_spi(Reflection)` helper for projecting the associated value of any enum into an existential `Any`. We can eliminate a bunch of work we're currently doing by always projecting into the field type described by the runtime and _then_ we can further attempt to cast to the extracted payload.
Fixes #83.
There are probably some performance improvements that can be made, but the benchmarks appear to perform as well as they do on `main`. 
/cc @mayoff
=> Add reflection API for projecting into any enum value

Sources/CasePaths/CasePath.swift, Sources/CasePaths/Internal/TypeName.swift, Sources/CasePaths/XCTUnwrap.swift, Tests/CasePathsTests/XCTModifyTests.swift
We can take a utility function from [Custom
Dump](https://github.com/pointfreeco/swift-custom-dump) to improve the output of failure messages.
=> XCT{Unwrap,Modify}: Improve type name debugging

Sources/CasePaths/EnumReflection.swift, Sources/CasePaths/XCTUnwrap.swift, Tests/CasePathsTests/XCTModifyTests.swift, Tests/CasePathsTests/XCTUnwrapTests.swift
Cleans up the APIs and messaging for `XCTModify`/`XCTUnwrap`.
=> Add more failure message context to XCT helpers

.github/workflows/ci.yml, Tests/CasePathsTests/CasePathsTests.swift
We want to setup Windows CI for all of the Pointfree repos that are used in TCA to ensure that we have cross platform compatibility going forward (or at least to ensure that nothing breaks).
=> Adding Windows CI

Sources/CasePaths/EnumReflection.swift, Sources/CasePaths/Operators.swift
Pretty sure these doc notes were just accidentally copy-pasted from the void variant of the operator, because these two deal with actual values. I replaced it with a note from elsewhere documenting that these should be used indeed only with case initializers.
=> 📝 Fix doc note of non-void `/` operators

Sources/CasePaths/EnumReflection.swift
issues/61708 was fixed in swift 5.8
--refer links below--
https://github.com/apple/swift/pull/61966
https://github.com/apple/swift/commits/swift-5.8-RELEASE?after=f9611bc8e745b1b9a98d494236adb6d6c739fe97+1364&branch=swift-5.8-RELEASE&qualified_name=refs%2Ftags%2Fswift-5.8-RELEASE
=> apply workaround for 61708 only when swift<5.8

.github/workflows/ci.yml
We have started getting strange failures in Windows CI, but only when running in release mode, not debug. So, let's disable for now.
=> Disable windows CI for release.

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
When using the [`package`](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md) access modifier, a compile error occurred due to differences in property access levels.
`package` access modifier is now given a modifier as well as public access modifier.
=> Modify isNeededAccessLevelModifier result conditions

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
I ran into a compile error `"Tuple element cannot have two labels"` with some wildcard arguments in enum cases during our TCA 1.4.0 migration. 
I've sorted it out by setting firstName to nil in associatedValue.parameter for those wildcards.
If you've got a neater way to handle this, I'm all ears for suggestions!
=> Fix compile error caused by wildcard argument usage

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
This PR updates the macro code to allow it to generate case paths for cases which are conditionally compiled. For example:
```
@CasePathable enum Foo {
case bar
#if DEBUG
case debugCase
#endif
}
```
_Currently released implementation would generate the case path only for `bar`._
I'm working on a project where we use TCA. Because we share the code between iOS and macOS we have a few places where one platform has some additional actions (features) and they are wrapped with `#if os`.
What do you think? Would it be useful? Appreciate any feedback 🙂
=> Support enums with cases wrapped in #if

Sources/CasePaths/CasePathable.swift
Updated the signature to be a `PartialCaseKeyPath` which is all that is required for this function to work.
Makes it possible to write algorithms that operate on a collection of case key paths for a given type, for example:
```swift
extension CasePathable {
func isOneOf<CaseKeyPaths: Sequence>(_ keyPaths: CaseKeyPaths) -> Bool where CaseKeyPaths.Element == PartialCaseKeyPath<Self> {
keyPaths.contains(where: { self.is($0) })
}
}
```
=> Support matching on partial key paths using `is`

Sources/CasePaths/CasePathable.swift, Sources/swift-case-paths-benchmark/main.swift
Case key paths are slightly expensive to resolve since they need to create a `Case` value under the hood, and apply a dynamic key path to it to build up something composed. Because dynamic member lookup only ever cares about one component at a time, we can bypass this extra work and access the case path directly.
=> Performance: Access case path directly in dynamic member lookup

Sources/CasePaths/CasePathable.swift, Sources/swift-case-paths-benchmark/Common.swift, Sources/swift-case-paths-benchmark/Foo.swift, Sources/swift-case-paths-benchmark/main.swift
Let's add updated benchmarks to get a better understanding of the performance of case key paths vs. reflection-based case paths.
While case key paths bring a number of improvements to case paths, including better ergonomics and the ability to utilize dynamic member lookup along enum cases, they are currently a bit slower than reflection-based case paths.
The performance of reflection-based case paths is the result of a long journey of improvements, so this shouldn't be super surprising, and case key paths are still plenty fast compared to earlier case paths.
These benchmarks will help us measure improvements to case key paths over time.
=> Add updated benchmarks

Sources/CasePaths/Optional+CasePathable.swift, Tests/CasePathsTests/CasePathsTests.swift
Swift allows us to omit `.some` and does the work to implicitly wrap optionals for us:
```swift
let _: Int? = 42
// Equivalent to:
let _: Int? = .some(42)
```
So why not do the same in case paths? Instead of forcing `.some` when going through an optional, we can go directly:
```swift
enum Foo { case bar(Bar?) }
enum Bar { case baz(Int) }
// Before:
\Foo.Cases.bar.some.baz
// After:
\Foo.Cases.bar.baz
```
=> Add Optional case path for chaining into `some` case

Sources/CasePaths/Never+CasePathable.swift, Sources/CasePaths/Optional+CasePathable.swift, Sources/CasePaths/Result+CasePathable.swift
Turns out we only need the `Case` overload.
Also documenting a few paths while I go.
=> Simplify optional flattening

Sources/CasePaths/Optional+CasePathable.swift, Tests/CasePathsTests/CasePathsTests.swift
While #139/#140 added support for flattening optionals, this PR adds support for chaining _into_ optionals. This is useful for when an API takes a case key path to an optional value, but you want to chain into another value and keep things optional.
=> Add case path for optional chaining

Sources/CasePaths/CasePathable.swift, Tests/CasePathsTests/CasePathsTests.swift
Hi there, I found a bug in `is(_:)`.
In version 1.2.0, the handling of optional associated values has been improved. Specifically, the subscript(case:) now correctly returns a value without unnecessarily wrapping it in an additional Optional layer when the associated value is already an Optional. However, this improvement has introduced a significant bug.
Consider the following enum as an example:
```Swift
enum Foo {
case c1
case c2(String?)
}
```
When using the is(_:) method with c2's associated value set to nil, like so:
```Swift
Foo.c2(nil).is(\.c2) // false
```
The expected result would be true, but it incorrectly returns false. This is a direct consequence of the changes in version 1.2.0. Prior to this change, the value of `self[case: keyPath]`  used in the implementation of `is(_:)` …
=> Fix fatal bug in `is(_:)`

Sources/CasePaths/CasePathable.swift, Tests/CasePathsTests/CasePathsTests.swift
Currently, sending an `Any` value to `PartialCaseKeyPath.callAsFunction` will always fail because the existential isn't opened. This should fix that.
=> Open existentials sent to `PartialCaseKeyPath.callAsFunction`

Sources/CasePaths/CasePathable.swift, Sources/CasePaths/Optional+CasePathable.swift, Tests/CasePathsTests/CasePathsTests.swift
We recently added code that can flatten optionals in a couple of ways, but because these methods weren't disfavored, they take precedent and can produce case key paths incapable of expressing what you want, like the ability to embed a optional in an case that contains an optional:
```swift
@CasePathable
enum Foo {
case bar(Int?)
}
let kp = \Foo.Cases.bar  // CaseKeyPath<Foo, Int>, not <Foo, Int?>
kp(nil)  // 'nil' is not compatible with expected argument type 'Int'
```
This PR disfavors these overloads to allow you to flatten optionals contextually, but by default will leave them alone.
It also fixes a bug in `PartialCaseKeyPath.callAsFunction` that would prevent non-optionals from being promoted to optionals in cases that expect them:
```swift
let kp: PartialCaseKeyPath<Foo> = \.bar
// …
```
=> Fixes around optionals and partial case key paths

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
This applies `public` access to everything inside the enum, which will gracefully degrade to the access control of the context (fixes #148).
This also applies the availability clause of the declaration to the extension.
=> Macro fixes

Sources/CasePaths/CasePathable.swift, Sources/CasePaths/Documentation.docc/CasePathable.md, Tests/CasePathsTests/CasePathsTests.swift
While we should prohibit directly assigning a value through a case:
```swift
state.loggedIn = User(name: "Blob")  // 🛑
```
We can allow optional-chaining into a case's sub-value via an overload and some disfavoring:
```swift
state.loggedIn?.name = "Blob"  // ✅
```
=> Allow writability when chaining into a dynamic case

Sources/CasePathsMacros/CasePathableMacro.swift
It is currently applied to code that has been rewritten, which breaks the Xcode integration and hides the error. By delaying the rewriting, we can restore the position of the error when it's emitted.
=> Fix overloaded case diagnostic

Sources/CasePaths/Never+CasePathable.swift, Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePaths copy.xctestplan, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
- Adds a deprecated overload of `.never` that calls out when an enum is not case-pathable and thus does not have any of its cases available via key path syntax.
- Propagates case documentation to the generated case path. This makes autocomplete, etc., a bit nicer, as it explains to the user which case you are completing to when it is documented.
=> Quality-of-life improvements

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
With v1.3.1 documentation is now also included for the generated `AllCasePaths` struct.
In order to achieve this the leadingTrivia for each case is appended to the generated properties. To ensure indentation matches, the code discards leading whitespaces from the trivia.
When determining how many characters to trim, the code loops over each line in the leadingTrivia, discarding empty lines and counting the amount of prefixed whitespaces. The smallest value counted is then taken and used as the amount of whitespace to trim from each line.
There is an issue in this last bit of logic where lines without prefixed whitespaces are always ignored. This will cause these lines to be trimmed erroneously. Take the following example:
```swift
@CasePathable
enum MyEnum {
// TODO: Implement this case …
```
=> leadingTrivia indentation trimming calculation should not discard zero values

Sources/CasePaths/CasePathable.swift, Sources/CasePaths/Documentation.docc/CasePathable.md, Sources/CasePaths/Optional+CasePathable.swift, Tests/CasePathsTests/CasePathsTests.swift
Swift optional promotion is sometimes succeeding to return `.some(.none)` where it should be returning `.none`.
=> Fix Optional dynamic member lookup

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
Fixes warnings due to unreachable code introduced in [1.4.0](https://github.com/pointfreeco/swift-case-paths/releases/tag/1.4.0):
For example:
```swift
@CasePathable enum Foo {}
```
Produces this expansion (compiler warnings added as code comments by me)
```swift
enum Foo: CasePathable {
public struct AllCasePaths: Sequence {
public subscript(root: Foo) -> PartialCaseKeyPath<Foo> {
return \.never // ⚠️ warning: will never be executed
// 'root' is of type 'Foo' which cannot be constructed because it
// is an enum with no cases
}
public func makeIterator() -> IndexingIterator<[PartialCaseKeyPath<Foo>]> {
let allCasePaths: [PartialCaseKeyPath<Foo>] = []
return allCasePaths.makeIterator()
}
}
public static var allCasePaths: AllCasePaths { AllCasePaths() }
}
```
We can fix this warning by …
=> Fix build warning when `@CasePathable` is applied to enums with no cases

Sources/CasePaths/Optional+CasePathable.swift, Sources/CasePaths/Result+CasePathable.swift
This just cleans up the case path iteration for optional/result to be more consistent with the macro, which doesn't hold onto the array as storage, but rather lazily creates it.
=> Make `Optional`/`Result` more consistent with macro-generated code

Package.swift, Package@swift-6.0.swift
The repo has been moved to the new `swiftlang` org. This fixes warnings when using other dependencies that already have an updated reference:
=> Point to `swiftlang/swift-syntax`

Sources/CasePaths/CasePathIterable.swift, Sources/CasePaths/CasePathReflectable.swift, Sources/CasePaths/Documentation.docc/CasePathable.md, Sources/CasePaths/Macros.swift, Sources/CasePaths/Never+CasePathable.swift, Sources/CasePaths/Optional+CasePathable.swift, Sources/CasePaths/Result+CasePathable.swift, Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift, Tests/CasePathsTests/CaseSetTests.swift
While the macro recently introduced iteration (https://github.com/pointfreeco/swift-case-paths/pull/159) and "reflection" (https://github.com/pointfreeco/swift-case-paths/pull/158), there's no way to abstract over it. Adding it directly to the `CasePathable` protocol would be potentially source breaking, so instead we can introduce some new protocols.
=> Add `CasePathIterable` and `CasePathReflectable` protocols 

Package.resolved, Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
Sendability meant losing the `Enum.case` shorthand for `{ Enum.case($0) }`, which meant introducing a warning when `type(of: $0) == Never.self`. Looks like we can suppress this warning, though, and it also luckily looks like this _only_ affects embedding `Never` directly (embedding enums that only contain `Never` does not trigger a warning).
=> Avoid warning when embedding `Never` cases

Sources/CasePaths/CasePathable.swift, Sources/CasePaths/Optional+CasePathable.swift
A regression in recent snapshots is causing compiler crashes.
https://github.com/swiftlang/swift/issues/75244
Let's disable these code paths for now while we wait for resolution.
=> Disable sendable dynamic key path lookup for now

Package.resolved, Sources/CasePaths/AnyCasePath.swift, Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift, Tests/CasePathsTests/MacroTests.swift
These closures are effectively sendable since they're "thin", but the initializer breaks the point-free style, and introduces unfortunate warnings when dealing with uninhabited enums.
=> Use Point-Free syntax to avoid uninhabited warnings

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
This would be the general idea with a very rough implementation. Basically just generating a `typealias` for every associated value that contains an `Element` type.
It could be refined to check if there is specifically a type named `Element` used since this will just catch anything containing element. 
I think the macro definition can also better specify what names the `typealias` can have so it doesnt need to be arbitrary?
Like I said just a very rough idea.
edit: Sorry just saw that my formatter ran a bit wild there
=> fix for Element compiler issue

.github/workflows/ci.yml, Tests/CasePathsTests/DeprecatedTests.swift
We are moving to Swift SDK-style installation on the development branch, and `swift test` with static stdlib is broken in obsoleting toolchain-style installation now.
Verified it works here ✅  https://github.com/kateinoigakukun/swift-case-paths/actions/runs/10591664518/job/29349506477
=> Follow-up Wasm CI integration

.github/workflows/ci.yml, .github/workflows/format.yml, Package.resolved
Previously, running `make test-swift` would result in build errors with Xcode 16 selected, i.e. 
Updated several dependencies to resolve this, and have the command complete successfully. 
Additionally, updated CI to ensure Xcode 16 is being used across actions.
=> Update dependencies, to avoid build issues with Xcode 16 on `make test-swift`

.github/workflows/ci.yml, Makefile, Package.resolved, Sources/CasePathsMacros/CasePathableMacro.swift
- Add `build-for-library-evolution` target to the Makefile. This replicates an issue I'm seeing in our project building with Xcode 16, i.e. - 
- Updates some dependencies to address various errors outside of this repository affecting the `build-for-library-evolution` target
- Adds `@unknown default` to one switch statement inside this project causing some issues
Happy to add CI around this target if desired; let me know what you think!
=> Create a Makefile target simulating building for Library Evolution; address issues with Xcode 16 running it

.github/workflows/ci.yml
The old snapshots did not support the renamed `swiftLanguageModes` Package.swift parameter.
=> Fix SwiftWasm CI

.github/workflows/ci.yml
* Use `v1` version instead of `v1.0.0` 
* Use major versions only instead of checking against all versions.
=> Update Macro Compatibility Check

Sources/CasePaths/Optional+CasePathable.swift
This PR is aimed at improving ergonomics for `is` checks specifically in TCA. Destinations and other pieces of CasePathable state can often be optional in TCA, and so out of the box the `CasePathable.is` function requires either unwrapping the optional state or tacking on `== true` to compile. I defined this extension in my own codebase a while ago to make that syntax a bit nicer to read, so as I was copying it over to another project I thought it might be worth submitting for inclusion right in the library itself
=> Added a convenience `is` function for optional CasePathable values

.github/workflows/ci.yml, Package.resolved, Tests/CasePathsTests/CasePathableTests.swift, Tests/CasePathsTests/CasePathsTests.swift
Compile with 
```
OMIT_MACRO_TESTS=1 /Library/Developer/Toolchains/swift-6.0.2-RELEASE.xctoolchain/usr/bin/swift build --swift-sdk aarch64-unknown-linux-android24 --build-tests
```
Copy to Android device
Run with
```
./swift-case-pathsPackageTests.xctest
```
=> Compile for Android

Sources/CasePaths/CasePathable.swift, Sources/CasePaths/Internal/KeyPath+Sendable.swift, Sources/CasePaths/Optional+CasePathable.swift, Tests/CasePathsTests/CaseSetTests.swift
Dynamic member lookup does not currently support sendable key paths, and we've had commented-out code as a result, but let's clean it up in favor of solutions employed in our other repos.
=> Clean up dynamic member lookup key path sendability

Sources/CasePathsMacros/CasePathableMacro.swift, Tests/CasePathsMacrosTests/CasePathableMacroTests.swift
Just in case there is a local `Sequence` type, etc.
=> Fully qualify types introduced by macro

Sources/CasePathsCore/Optional+CasePathable.swift
Optional chaining into `modify` can lead to quietly losing issues when you intend to modify something. Let's take advantage of the trick introduced in #204 to avoid losing the result via optional chaining.
=> Add `Optional.modify` overload

Package.swift, Package@swift-6.0.swift
- [Stable swift-syntax@6.1 is released.](https://github.com/swiftlang/swift-syntax/releases/tag/601.0.0)
- https://github.com/search?q=org%3Apointfreeco+swift-syntax+601+path%3A*.swift&type=code
=> Support stable 6.1 in swift-syntax

.github/workflows/ci.yml
To reduce duplicate efforts I am deprecating my GitHub action now that skiptool has one that does the same and more. 
It ran successfully here: https://github.com/johankool/swift-case-paths/actions/runs/13339711902
=> Use skiptool's action instead
